spring:
  application:
    name: Backend
  servlet:
    multipart:
      max-file-size: 10MB
application:
  s3:
    bucket:
      name: 'eurekapp-temp'
  openai:
    url: 'https://api.openai.com/v1/'
    api-key: ${OPENAI_SECRET_KEY}
  pinecone:
    api-key: ${PINECONE_SECRET_KEY}
    namespace: 'image-description'
  jwt:
    sign-key: ${JWT_SIGN_KEY}
  mailtrap:
    host: 'live.smtp.mailtrap.io'
    user: 'api'
    password: ${MAILTRAP_KEY}
    port: '587'