spring:
  application:
    name: Backend

application:
  s3:
    bucket:
      name: 'eurekapp-bucket'
  openai:
    api:
      key: ${OPENAI_SECRET_KEY}
  pinecone:
    api:
      key: ${PINECONE_SECRET_KEY}
    namespace: 'image-description'
