spring:
  application:
    name: Backend
  servlet:
    multipart:
      max-file-size: 10MB
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
application:
  s3:
    bucket:
      name: 'eurekapp-temp'
  openai:
    url: 'https://api.openai.com/v1/'
    api-key: ${OPENAI_SECRET_KEY}
  pinecone:
    api-key: ${PINECONE_SECRET_KEY}
  jwt:
    sign-key: ${JWT_SIGN_KEY}
  mailtrap:
    host: 'live.smtp.mailtrap.io'
    user: 'api'
    password: ${MAILTRAP_KEY}
    port: '587'
  weaviate:
    url: 'localhost:8081'
    schema: 'http'